Feature/128 full crud operation
panoptes-organization/panoptes pull request #129
Opened 2020-12-04 23:13 UTC by drekoumis

Change API use CRUD operation for delete and rename. Create API for rename wf and job . Create some API test for delete and rename wf. Change return API codes.

2020-12-05 14:52 UTC, dafentoulis approved these changes
Really good job @drekoumis!
I added API related changes, I think @agardelakos  can have a better look at the python - testing part.

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'msg': "Workflow not found"}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +                        'count': 0}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'msg': 'Job not found'}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +                        'count': 0}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'msg': "Workflow not found"}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'msg': "Bad Request"}), 400
same here for 400, it is already a BAD REQUEST

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'msg': 'Job not found'}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +                        'count': 0}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +                        '. Please check if workflow ' + workflow_id + ' exists.'}), 404
I think message not needed here, 404 is self-explanatory

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'msg': 'You cannot delete Running Workflow '}), 403
Change message to "Workflow is running"

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'msg': 'Database error'}), 500
Message is needed here, but it should describe the problem better

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'msg': 'Database clean up is complete'}), 200
No message needed, just status code 204.

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'error': 500, 'msg': 'Database error'}), 500
Message is needed here, but it should describe the problem better

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'error': 510, 'msg': 'Database is empty'}), 510
No message needed, status should be 410

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'msg': "Delete Complete Correctly ", 'Workflow': workflow_id}), 200
No message needed, just status code 204.

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +        return jsonify({'msg': "Bad Request"}), 400
same here for 400, it is already a BAD REQUEST

2020-12-05 14:52 UTC, dafentoulis commented on panoptes/routes/api.py
> +            return jsonify({'error': 500, 'msg': 'Database error'}), 500
Message is needed here, but it should describe the problem better

2020-12-07 10:32 UTC, dafentoulis approved these changes

2020-12-07 20:29 UTC, fgypas requested changes
It seems that the API changed. @drekoumis Can you please, document the changes in the API section of the README.md?

2020-12-08 20:02 UTC, fgypas approved these changes
LGTM !!!

2020-12-08 20:08 UTC, merged